/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard.settings'
import { Route as DashboardRevenueRouteImport } from './routes/dashboard.revenue'
import { Route as DashboardReservationsRouteImport } from './routes/dashboard.reservations'
import { Route as DashboardPropertiesRouteImport } from './routes/dashboard.properties'
import { Route as DashboardInboxRouteImport } from './routes/dashboard.inbox'
import { Route as DashboardHousekeepingRouteImport } from './routes/dashboard.housekeeping'
import { Route as DashboardGuestsRouteImport } from './routes/dashboard.guests'

const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardRevenueRoute = DashboardRevenueRouteImport.update({
  id: '/revenue',
  path: '/revenue',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardReservationsRoute = DashboardReservationsRouteImport.update({
  id: '/reservations',
  path: '/reservations',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPropertiesRoute = DashboardPropertiesRouteImport.update({
  id: '/properties',
  path: '/properties',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardInboxRoute = DashboardInboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardHousekeepingRoute = DashboardHousekeepingRouteImport.update({
  id: '/housekeeping',
  path: '/housekeeping',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardGuestsRoute = DashboardGuestsRouteImport.update({
  id: '/guests',
  path: '/guests',
  getParentRoute: () => DashboardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/pricing': typeof PricingRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/dashboard/guests': typeof DashboardGuestsRoute
  '/dashboard/housekeeping': typeof DashboardHousekeepingRoute
  '/dashboard/inbox': typeof DashboardInboxRoute
  '/dashboard/properties': typeof DashboardPropertiesRoute
  '/dashboard/reservations': typeof DashboardReservationsRoute
  '/dashboard/revenue': typeof DashboardRevenueRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/pricing': typeof PricingRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/dashboard/guests': typeof DashboardGuestsRoute
  '/dashboard/housekeeping': typeof DashboardHousekeepingRoute
  '/dashboard/inbox': typeof DashboardInboxRoute
  '/dashboard/properties': typeof DashboardPropertiesRoute
  '/dashboard/reservations': typeof DashboardReservationsRoute
  '/dashboard/revenue': typeof DashboardRevenueRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard': typeof DashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/pricing': typeof PricingRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/dashboard/guests': typeof DashboardGuestsRoute
  '/dashboard/housekeeping': typeof DashboardHousekeepingRoute
  '/dashboard/inbox': typeof DashboardInboxRoute
  '/dashboard/properties': typeof DashboardPropertiesRoute
  '/dashboard/reservations': typeof DashboardReservationsRoute
  '/dashboard/revenue': typeof DashboardRevenueRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/pricing'
    | '/sign-in'
    | '/sign-up'
    | '/dashboard/guests'
    | '/dashboard/housekeeping'
    | '/dashboard/inbox'
    | '/dashboard/properties'
    | '/dashboard/reservations'
    | '/dashboard/revenue'
    | '/dashboard/settings'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/pricing'
    | '/sign-in'
    | '/sign-up'
    | '/dashboard/guests'
    | '/dashboard/housekeeping'
    | '/dashboard/inbox'
    | '/dashboard/properties'
    | '/dashboard/reservations'
    | '/dashboard/revenue'
    | '/dashboard/settings'
    | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/pricing'
    | '/sign-in'
    | '/sign-up'
    | '/dashboard/guests'
    | '/dashboard/housekeeping'
    | '/dashboard/inbox'
    | '/dashboard/properties'
    | '/dashboard/reservations'
    | '/dashboard/revenue'
    | '/dashboard/settings'
    | '/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  PricingRoute: typeof PricingRoute
  SignInRoute: typeof SignInRoute
  SignUpRoute: typeof SignUpRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/revenue': {
      id: '/dashboard/revenue'
      path: '/revenue'
      fullPath: '/dashboard/revenue'
      preLoaderRoute: typeof DashboardRevenueRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/reservations': {
      id: '/dashboard/reservations'
      path: '/reservations'
      fullPath: '/dashboard/reservations'
      preLoaderRoute: typeof DashboardReservationsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/properties': {
      id: '/dashboard/properties'
      path: '/properties'
      fullPath: '/dashboard/properties'
      preLoaderRoute: typeof DashboardPropertiesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/inbox': {
      id: '/dashboard/inbox'
      path: '/inbox'
      fullPath: '/dashboard/inbox'
      preLoaderRoute: typeof DashboardInboxRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/housekeeping': {
      id: '/dashboard/housekeeping'
      path: '/housekeeping'
      fullPath: '/dashboard/housekeeping'
      preLoaderRoute: typeof DashboardHousekeepingRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/guests': {
      id: '/dashboard/guests'
      path: '/guests'
      fullPath: '/dashboard/guests'
      preLoaderRoute: typeof DashboardGuestsRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardGuestsRoute: typeof DashboardGuestsRoute
  DashboardHousekeepingRoute: typeof DashboardHousekeepingRoute
  DashboardInboxRoute: typeof DashboardInboxRoute
  DashboardPropertiesRoute: typeof DashboardPropertiesRoute
  DashboardReservationsRoute: typeof DashboardReservationsRoute
  DashboardRevenueRoute: typeof DashboardRevenueRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardGuestsRoute: DashboardGuestsRoute,
  DashboardHousekeepingRoute: DashboardHousekeepingRoute,
  DashboardInboxRoute: DashboardInboxRoute,
  DashboardPropertiesRoute: DashboardPropertiesRoute,
  DashboardReservationsRoute: DashboardReservationsRoute,
  DashboardRevenueRoute: DashboardRevenueRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  PricingRoute: PricingRoute,
  SignInRoute: SignInRoute,
  SignUpRoute: SignUpRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
